<a href="https://colab.research.google.com/github/Yoon2596/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%EA%B3%BC%EC%A0%9C/%EA%B3%BC%EC%A0%9C_0603.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1. 주어진 df의 날짜 리스트를 datetime 형식으로 변환하고, 변환된 데이터프레임의 년도, 월, 일 열을 추가하시오.

In [ ]:
import pandas as pd

# 날짜 문자열 리스트
date_list = ['2023-01-01', '2023-02-15', '2023-03-30']

# 데이터프레임 생성
df = pd.DataFrame(date_list, columns=['date'])
df

         date
0  2023-01-01
1  2023-02-15
2  2023-03-30

In [ ]:
df_datetime = pd.to_datetime(df['date'])
print(df_datetime)
df.set_index(df_datetime, inplace=True)
df['year'] = df.index.year
df['month'] = df.index.month
df['day'] = df.index.day
# df.drop(columns=[0], axis=1)
print(df)
df.info()

date
2023-01-01   2023-01-01
2023-02-15   2023-02-15
2023-03-30   2023-03-30
Name: date, dtype: datetime64[ns]
                  date  year  month  day
date
2023-01-01  2023-01-01  2023      1    1
2023-02-15  2023-02-15  2023      2   15
2023-03-30  2023-03-30  2023      3   30
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3 entries, 2023-01-01 to 2023-03-30
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      object
 1   year    3 non-null      int32
 2   month   3 non-null      int32
 3   day     3 non-null      int32
dtypes: int32(3), object(1)
memory usage: 84.0+ bytes

In [ ]:
# 강사님 버전 문제1
# 문자열을 datetime으로 변환
df['date'] = pd.to_datetime(df['date'])

# 년, 월, 일 열 추가
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

print(df)

        date  year  month  day
0 2023-01-01  2023      1    1
1 2023-02-15  2023      2   15
2 2023-03-30  2023      3   30

Task2. 주어진 월간 데이터를 타임스탬프로 변환하고, 변환된 결과에서 시간을 제외한 날짜만 출력하시오.

In [ ]:
import pandas as pd

# 문자열을 Period로 변환
period_data = pd.Series(['2023-01', '2023-02', '2023-03'], name='period')
period_data

0    2023-01
1    2023-02
2    2023-03
Name: period, dtype: object

In [ ]:
# data = {'value' : range(3)}
df_date = pd.to_datetime(period_data)
print(df_date)

# date = pd.to_datetime(df['period'])

0   2023-01-01
1   2023-02-01
2   2023-03-01
Name: period, dtype: datetime64[ns]

In [ ]:
# 문자열을 period로 변환
period_data = period_data.astype('period[M]')
print(period_data, '\n')

# period를 Timestamp로 변환
timestamp_data = period_data.apply(lambda x: x.to_timestamp())
print(timestamp_data, '\n')

# 날짜만 출력
print(timestamp_data)

0    2023-01
1    2023-02
2    2023-03
Name: period, dtype: period[M]

0   2023-01-01
1   2023-02-01
2   2023-03-01
Name: period, dtype: datetime64[ns]

0   2023-01-01
1   2023-02-01
2   2023-03-01
Name: period, dtype: datetime64[ns]

Task3. 주어진 날짜 데이터 시리즈를 분기로 변환하고, 각 분기별로 데이터의 개수를 출력하세요.

In [ ]:
import pandas as pd

# 날짜 데이터 시리즈
date_series = pd.Series(pd.date_range('2023-01-01', '2023-12-31', freq='M'))
date_series

0    2023-01-31
1    2023-02-28
2    2023-03-31
3    2023-04-30
4    2023-05-31
5    2023-06-30
6    2023-07-31
7    2023-08-31
8    2023-09-30
9    2023-10-31
10   2023-11-30
11   2023-12-31
dtype: datetime64[ns]

In [ ]:
# 날짜 데이터를 분기로 변환
quarter_data = date_series.dt.to_period('Q')
print(quarter_data, '\n')
# 각 분기별 데이터 개수 세기
quarter_counts = quarter_data.value_counts().sort_index()
print(quarter_counts)

0     2023Q1
1     2023Q1
2     2023Q1
3     2023Q2
4     2023Q2
5     2023Q2
6     2023Q3
7     2023Q3
8     2023Q3
9     2023Q4
10    2023Q4
11    2023Q4
dtype: period[Q-DEC]

2023Q1    3
2023Q2    3
2023Q3    3
2023Q4    3
Freq: Q-DEC, Name: count, dtype: int64

Task4. train.csv 파일로 생존자 예측 모델 생성을 위한 분석용 데이터 셋을 작성하세요.

In [2]:
import pandas as pd

# 데이터프레임 읽기
file_path = '/content/drive/MyDrive/KDT_240424/m3_분석_라이브러리/pandas/m_3_datas/train.csv'

# df = pd.read_csv(file_path)
df = pd.read_csv(file_path)

# 파일 확인
print(df,'\n')
df.info()# 데이터프레임 읽기

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# df['Ticket'].describe()
print(df['Name'], df['Ticket'], df['Pclass'])

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object 0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object 0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [ ]:
print(df.isnull().sum())
# 아이디랑 na 있는 컬럼 모두 제거
df.drop(columns = ['PassengerId', 'Age', 'Cabin', 'Embarked'], inplace=True)
df.dropna()
df.info()

# 타입이 object인 것만 뽑음
encoding_columns = ['Name', 'Sex', 'Ticket']

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    object
 7   Fare      891 non-null    float64
dtypes: float64(1), int64(4), object(3)
memory usage: 55.8+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder

# print(df[df['Name'].str.contains('Mr')])
# print(df[df['Name'].str.contains('Mrs')])
# print(df[df['Name'].str.contains('Miss')].value_counts())
# print(df)
# df1 = df['Name'].str.startswith("Mi")
# print(df1)
# df['T_string'] = df['T_string'].str.extract(r'(\d+)')
# print(df['T_string'])

# Label Encoding
print(encoding_columns)
# label = []
dics = {}
for col in encoding_columns:

    le = LabelEncoder()
    # items = list(df[encoding_columns])
    # le.fit(items)
    # labels = le.transform(items)
    # df[column] = labels
    df[col] = le.fit_transform(df[col])
    # dics[col] = [le.classes_, le]

df.head(10)
# df.info()

['Name', 'Sex', 'Ticket']

   Survived  Pclass  Name  Sex  SibSp  Parch  Ticket     Fare
0         0       3   108    1      1      0     523   7.2500
1         1       1   190    0      1      0     596  71.2833
2         1       3   353    0      0      0     669   7.9250
3         1       1   272    0      1      0      49  53.1000
4         0       3    15    1      0      0     472   8.0500
5         0       3   554    1      0      0     275   8.4583
6         0       1   515    1      0      0      85  51.8625
7         0       3   624    1      3      1     395  21.0750
8         1       3   412    0      0      2     344  11.1333
9         1       2   576    0      1      0     132  30.0708

In [ ]:
# sibsp와 parch 합쳐서 가족 규모 변수 생성
df['family_size'] = df['SibSp'] + df['Parch'] + 1   # 자기 자신 포함
df.drop(columns=['SibSp', 'Parch'], inplace=True)

# fare를 3개 범주로 변환
fare_bins = [0, 22, 45, 150]
fare_labels = ['Low', 'Medium', 'High']
df['fare_group'] = pd.cut(df['Fare'], bins = fare_bins, labels=fare_labels)
df.drop(columns=['Fare'], inplace=True)

# # name를 3개 범주로 변환
# name_bins = [0, 100, 500, 1000]
# name_labels = ['High', 'Medium', 'Low']
# df['name_group'] = pd.cut(df['Name'], bins = name_bins, labels=name_labels)
# df.drop(columns=['Name'], inplace=True)
# df.head(10)

# # ticket를 3개 범주로 변환
# ticket_bins = [0, 100, 200, 1000]
# ticket_labels = ['High', 'Medium', 'Low']
# df['ticket_group'] = pd.cut(df['Ticket'], bins = ticket_bins, labels=ticket_labels)
# df.drop(columns=['Ticket'], inplace=True)
df.head(10)

   Survived  Pclass  Name  Sex  Ticket  family_size fare_group
0         0       3   108    1     523            2        Low
1         1       1   190    0     596            2       High
2         1       3   353    0     669            1        Low
3         1       1   272    0      49            2       High
4         0       3    15    1     472            1        Low
5         0       3   554    1     275            1        Low
6         0       1   515    1      85            1       High
7         0       3   624    1     395            5        Low
8         1       3   412    0     344            3        Low
9         1       2   576    0     132            2     Medium

In [ ]:
# Label Encoding
categorical_columns = ['fare_group']
dics = {}
for col in categorical_columns:

    le = LabelEncoder()
    # items = list(df[encoding_columns])
    # le.fit(items)
    # labels = le.transform(items)
    # df[column] = labels
    df[col] = le.fit_transform(df[col])
    # dics[col] = [le.classes_, le]

df.head(10)

   Survived  Pclass  Name  Sex  Ticket  family_size  fare_group
0         0       3   108    1     523            2           1
1         1       1   190    0     596            2           0
2         1       3   353    0     669            1           1
3         1       1   272    0      49            2           0
4         0       3    15    1     472            1           1
5         0       3   554    1     275            1           1
6         0       1   515    1      85            1           0
7         0       3   624    1     395            5           1
8         1       3   412    0     344            3           1
9         1       2   576    0     132            2           2

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 타겟 변수와 피처 변수 설정
X = df.drop('Survived', axis=1)
y = df['Survived']

# 학습 데이터와 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 크기 확인
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

# 랜덤 포레스트 모델 학습
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 성능 평가
print("Accuracy:", accuracy_score(y_test, y_pred))
# print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
# print("Classification Report:\n", classification_report(y_test, y_pred))

(712, 6) (179, 6) (712,) (179,)
Accuracy: 0.8324022346368715