<a href="https://colab.research.google.com/github/Yoon2596/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/pandas_4_%EB%82%A0%EC%A7%9C(0603).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Contents
- 날짜 변환 : to_datetime, to_timestamp, to_period
- 날짜 생성 : date_range, period_range
- 날짜 인덱싱, 필터링, 집계, 속성 접근, 정렬

####python, numpy, pandas 날짜 타입 비교 및 정리

- datetime은 python 설치 시 기본적으로 내장된 라이브러리로, 날짜를 쓸 것인지, 시간을 쓸 것인지, 날짜시간을 합쳐쓸 것인지에 따라 클래스가 분화되어 있는 것이 특징. 예를들어 '2021-3-16'을 표시하고 싶으면 date 클래스를 사용하고, '2021-3-16 12:34:21'를 표시하고 싶으면 'datetime' 클래스를 사용합니다.
- 반면 datetime64나 Timestamp는 각각 numpy, pandas 라이브러리에서 새로 정의한 날짜시간 클래스입니다. 이 둘은 numpy, pandas를 설치해야만 이용할 수 있고, 한 클래스로 날짜, 시간, 날짜시간을 모두 정의할 수 있는 것이 특징
- 날짜, 시간 타입은 일반적인 정수, 실수끼리 연산할 때와 달리 단위를 가지고 있는 점 때문에 시간의 차이를 저장하는 별도의 클래스가 있다는 특징. 이를 timedelta(타임델타)라고 하는데, 날짜, 시간은 특정 시점의 시각을 표시하는 용도이고(2021년 3월 16일), 타임델타는 기간 또는 시간 차이를 표시하는 용도(5일)

####파이썬 datetime 모듈
- 기본 개념: datetime 모듈은 날짜 및 시간을 다루는 기본적인 클래스들(date, time, datetime, timedelta, tzinfo)을 제공
- 날짜 생성 및 조작: 특정 날짜를 생성하거나 날짜 간의 차이를 계산하는 등의 기능을 수행
- 포맷팅: strftime()을 사용하여 날짜를 문자열로, strptime()을 사용하여 문자열을 날짜로 변환
- 시간대 처리: 시간대를 처리하는 기능을 포함하고 있지만, 별도의 라이브러리(pytz 등)의 도움이 필요

판다스
- 시계열 데이터 처리에 최적화: 판다스는 시계열 데이터 처리에 특화되어 있으며, 대량의 날짜 데이터를 빠르고 효율적으로 처리할 수 있다.
- DateTimeIndex: 판다스는 DateTimeIndex를 제공하여 시계열 데이터의 인덱싱과 슬라이싱을 간편하게 한다.
- 시간대 처리: 판다스는 내장된 시간대 처리 기능을 제공하며, 시간대 변환을 손쉽게 할 수 있다.
- 날짜 데이터 변환 및 조작: to_datetime() 함수로 다양한 형식의 날짜 문자열을 datetime 객체로 변환할 수 있다. 또한, resample, asfreq 등의 메서드로 시계열 데이터의 빈도를 변경하는 등 다양한 날짜 관련 조작을 지원.
- 통합된 데이터 처리: 판다스는 DataFrame이나 Series 내의 날짜 데이터를 다룰 때, 다른 데이터 유형과의 통합된 처리가 가능.

포인트
- 파이썬 datetime: 날짜 및 시간의 기본적인 처리에 적합하며, 작고 단순한 날짜 관련 작업에 이상적이다.
- 판다스: 대규모 데이터셋에서 복잡하고 고급 시계열 데이터 처리에 적합하며, 데이터 분석과 관련된 다양한 기능을 제공한다.
- 사용 사례에 따라 적절한 도구를 선택하는 것이 중요. 작은 규모의 기본적인 날짜 연산에는 datetime을, 복잡한 데이터셋과 시계열 분석에는 판다스를 사용하는 것이 일반적.

Python의 datetime 모듈을 사용한 날짜 처리 예시. 이 예제들은 datetime 모듈을 사용하여 날짜 및 시간 데이터를 다루는 기본적인 방법을 보여준다.

- 현재 날짜 및 시간 얻기: datetime.now()를 사용.
- 특정 날짜 및 시간 생성: datetime 객체를 직접 생성.
- 날짜 간 차이 계산: timedelta를 사용.
- 날짜 포맷팅: 날짜를 문자열로 변환하거나 문자열로부터 날짜를 파싱.
- 날짜와 시간 요소 접근: 날짜의 연도, 월, 일 등을 접근.

판다스를 사용한 날짜 처리의 예. 이 예제들은 판다스가 시계열 데이터를 어떻게 다룰 수 있는지 보여준다.

- 날짜 범위 생성: pd.date_range()를 사용하여 날짜 범위를 생성.
- 날짜 변환: 문자열을 pd.to_datetime()을 사용하여 날짜 객체로 변환.
- 시계열 데이터 생성: 날짜를 인덱스로 사용하는 시계열 데이터를 생성.
- 날짜 기반 필터링: 특정 날짜 조건을 만족하는 데이터를 필터링.
- 시계열 데이터 리샘플링: 월별 평균 등으로 데이터를 리샘플링.
- 이 코드를 실행하면, 판다스를 사용하여 날짜 데이터를 다양하게 처리하는 방법을 확인할 수 있다. 날짜 범위 생성, 날짜 변환, 시계열 데이터 처리 등은 데이터 분석에서 매우 유용하게 활용.

In [ ]:
# 문자열 형식의 날짜를 datetime 형식으로 변환하여 처리
import pandas as pd
date_str = '2022-06-03'
date_dt = pd.to_datetime(date_str)
print(date_dt)  #출력 : 2022-06-03-00:00:00
print(date_dt.date())   # date만 츨력하고 싶을 때
print(date_dt.time())   # 시간만 출력하고 싶을 때

2022-06-03 00:00:00
2022-06-03
00:00:00

In [ ]:
# 날짜 변환
dates = ['2022-06-01', '2022-06-03', '2022-06-03']
date_objects = pd.to_datetime(dates)
print('날짜 객체', date_objects)
print()

date_only_list = [date.date() for date in date_objects]
print(date_only_list)

날짜 객체 DatetimeIndex(['2022-06-01', '2022-06-03', '2022-06-03'], dtype='datetime64[ns]', freq=None)

[datetime.date(2022, 6, 1), datetime.date(2022, 6, 3), datetime.date(2022, 6, 3)]

Q. 다시 문자열로 바꾸어 보기 ['2022-06-01', '2022-06-03', '2022-06-03']

In [ ]:
# print(date_only_list)
# str_date = []
# for i, j in enumerate(date_only_list):
#     str_date.append(j)

# print(str_date)
# # str_date = date_only_list.to_datetime()
# # print(str_date)
dates = ['2022-06-01', '2022-06-03', '2022-06-03']
date_objects = pd.to_datetime(dates)
date_list = [date.strftime('%Y-%m-%d') for date in date_objects]
date_list

['2022-06-01', '2022-06-03', '2022-06-03']

In [ ]:
# pd.date_range 함수는 일정한 간격으로 날짜 범위를 생성하는데 사용
# pd.date_range 함수는 pandas에서 제공하지만 내부적으로 numpy의 날짜/시간 타입인 datetime64를 사용
date_range = pd.date_range(start='2024-06-01', end='2024-06-05')
print(date_range)

DatetimeIndex(['2024-06-01', '2024-06-02', '2024-06-03', '2024-06-04',
               '2024-06-05'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
# 날짜를 인덱스로 설정하여 데이터프레임을 구성하면 날짜를 기준으로 데이터 조작이 용이
data = {'date' : ['2022-06-01', '2022-06-02', '2022-06-03'], 'value' : [1, 2, 3]}
df = pd.DataFrame(data)
print(df, '\n')

# 타입 바꾸기
# df['date'] = pd.to_datetime(df['date'])

# 인덱스 설정
df.set_index('date', inplace=True)
print(df, '\n')
df.index.name=None
print(df, '\n')

         date  value
0  2022-06-01      1
1  2022-06-02      2
2  2022-06-03      3

            value
date
2022-06-01      1
2022-06-02      2
2022-06-03      3

            value
2022-06-01      1
2022-06-02      2
2022-06-03      3

In [ ]:
# 날짜를 인덱스로 설정한 데이터프레임에서는 특정 기간의 데이터를 쉽게 인덱싱하고 슬라이싱
# 특정 날짜의 데이터를 선택
print(df.loc['2022-06-03'])

# 날짜 범위 슬라이싱
print(df['2022-06-01' : '2022-06-02'])

value    3
Name: 2022-06-03, dtype: int64
            value
2022-06-01      1
2022-06-02      2

In [ ]:
# 불리언 조건식을 사용하여 날짜 범위를 필터링
date_range = pd.date_range(start='2022-06-01', end='2022-06-10')
date_series = pd.Series(date_range)
fd = date_series[(date_series >= '2022-06-01') & (date_series <= '2022-06-03')]
print(fd)

0   2022-06-01
1   2022-06-02
2   2022-06-03
dtype: datetime64[ns]

In [ ]:
# Pandas는 주어진 주기(일, 월, 분기 등)에 따라 데이터를 리샘플링 할 수 있는 기능을 제공
# resample 메소드를 사용하면 다양한 방법으로 데이터를 집계
date_range = pd.date_range(start='2022-06-01', periods=10, freq='D')
data = {'value' : range(10)}
df = pd.DataFrame(data, index=date_range)
print(df, '\n')

# 월별 데이터 합계 계산
monthly_sum = df.resample('M').sum()
print(monthly_sum)

            value
2022-06-01      0
2022-06-02      1
2022-06-03      2
2022-06-04      3
2022-06-05      4
2022-06-06      5
2022-06-07      6
2022-06-08      7
2022-06-09      8
2022-06-10      9

            value
2022-06-30     45

Q. 365일간 일당을 성과에 따라서 50 ~ 100 달러를 받는다. 월별 합계를 구하시오

In [ ]:
import random
import numpy as np

salary = []
for i in range(365):
    salary.append(np.random.randint(50, 100))

date_range = pd.date_range(start='2024-01-01', periods=365, freq='D')
data = {'paid' : salary}
df = pd.DataFrame(data, index=date_range)
print(df)

# 월별 데이터 합계 계산
monthly_sum = df.resample('M').sum()
print(monthly_sum)

            paid
2024-01-01    68
2024-01-02    54
2024-01-03    68
2024-01-04    81
2024-01-05    63
...          ...
2024-12-26    64
2024-12-27    87
2024-12-28    51
2024-12-29    54
2024-12-30    85

[365 rows x 1 columns]
            paid
2024-01-31  2249
2024-02-29  2100
2024-03-31  2344
2024-04-30  2182
2024-05-31  2376
2024-06-30  2276
2024-07-31  2276
2024-08-31  2302
2024-09-30  2145
2024-10-31  2258
2024-11-30  2263
2024-12-31  2193

In [ ]:
# 강사님 버전
import random
import numpy as np

date_range = pd.date_range(start='2024-01-01', periods=365, freq='D')
data = {'paid' : np.random.randint(50, 100, 365)}
df = pd.DataFrame(data, index=date_range)
print(df)

# 월별 데이터 합계 계산
monthly_sum = df.resample('M').sum()
print(monthly_sum)

            paid
2024-01-01    71
2024-01-02    53
2024-01-03    64
2024-01-04    83
2024-01-05    66
...          ...
2024-12-26    73
2024-12-27    82
2024-12-28    68
2024-12-29    57
2024-12-30    99

[365 rows x 1 columns]
            paid
2024-01-31  2331
2024-02-29  2267
2024-03-31  2257
2024-04-30  2213
2024-05-31  2481
2024-06-30  2266
2024-07-31  2412
2024-08-31  2310
2024-09-30  2263
2024-10-31  2250
2024-11-30  2201
2024-12-31  2187

In [ ]:
data = {'date' : ['2022-01-01', '2022-01-02', '2022-01-03'], 'value' : [1, 2, 3]}
df = pd.DataFrame(data)
print(df, '\n')

df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)
print(df)

         date  value
0  2022-01-01      1
1  2022-01-02      2
2  2022-01-03      3

            value
date
2022-01-01      1
2022-01-02      2
2022-01-03      3

In [ ]:
# Pandas의 datetime 형식 데이터는 다양한 속성에 접근 할 수 있다. 예를 들어 : 연도, 월, 일, 요일, 등을 쉽게 추출
df['year'] = df.index.year
df['month'] = df.index.month
df['day'] = df.index.day
df['day_of_week'] = df.index.dayofweek
print(df)

            value  year  month  day  day_of_week
date
2022-01-01      1  2022      1    1            5
2022-01-02      2  2022      1    2            6
2022-01-03      3  2022      1    3            0

In [38]:
# 데이터프레임 읽기
file_path = '/content/drive/MyDrive/KDT_240424/m3_분석_라이브러리/pandas/m_3_datas/stock-data.csv'

# df = pd.read_csv(file_path)
df = pd.read_csv(file_path)

# 파일 확인
print(df.head(),'\n')
df.info()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     object
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), object(1)
memory usage: 1.1+ KB

In [39]:
df['New_Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     object
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   New_Date  20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 1.2+ KB

In [6]:
df.head()

         Date  Close  Start   High    Low  Volume   New_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

Q. index와 열을 쓰는 경우로 년, 월, 일 컬럼을 따로 뽑아보기

In [ ]:
df.set_index('New_Date', inplace=True)
df['year'] = df.index.year
df['month'] = df.index.month
df['day'] = df.index.day
print(df.head())

                  Date  Close  Start   High    Low  Volume  year  month  day
New_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977  2018      7    2
2018-06-29  2018-06-29  10700  10550  10900   9990  170253  2018      6   29
2018-06-28  2018-06-28  10400  10900  10950  10150  155769  2018      6   28
2018-06-27  2018-06-27  10900  10800  11050  10500  133548  2018      6   27
2018-06-26  2018-06-26  10800  10900  11000  10700   63039  2018      6   26

In [ ]:
# 강사님 버전 (index 말고 접근자 : dt를 사용)
df['New_Date'] = pd.to_datetime(df['Date'])
print(df.head())
df['year'] = df['New_Date'].dt.year
df['month'] = df['New_Date'].dt.month
df['day'] = df['New_Date'].dt.day
print(df.head())

         Date  Close  Start   High    Low  Volume   New_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26
         Date  Close  Start   High    Low  Volume   New_Date  year  month  day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

In [15]:
df1 = df.copy()
df1.head()

# 컬럼 기준으로 년, 월, 일 분리
df1['year'] = df1['New_Date'].dt.year
df1['month'] = df1['New_Date'].dt.month
df1['day'] = df1['New_Date'].dt.day
df1.drop(columns = ['Date', 'New_Date'], inplace=True)
df1.head()

   Close  Start   High    Low  Volume  year  month  day
0  10100  10850  10900  10000  137977  2018      7    2
1  10700  10550  10900   9990  170253  2018      6   29
2  10400  10900  10950  10150  155769  2018      6   28
3  10900  10800  11050  10500  133548  2018      6   27
4  10800  10900  11000  10700   63039  2018      6   26

In [23]:
df2 = df.copy()
df2.head()

# 인덱스 기준으로 년, 월, 일 분리
df2.set_index('New_Date', inplace=True)
df2['year'] = df2.index.year
df2['month'] = df2.index.month
df2['day'] = df2.index.day
df2.drop('Date', axis=1, inplace=True)
df2.head()

            Close  Start   High    Low  Volume  year  month  day
New_Date
2018-07-02  10100  10850  10900  10000  137977  2018      7    2
2018-06-29  10700  10550  10900   9990  170253  2018      6   29
2018-06-28  10400  10900  10950  10150  155769  2018      6   28
2018-06-27  10900  10800  11050  10500  133548  2018      6   27
2018-06-26  10800  10900  11000  10700   63039  2018      6   26

In [40]:
df.head()
df.set_index('New_Date', inplace=True)
df.drop('Date', axis=1, inplace=True)
df.head()

            Close  Start   High    Low  Volume
New_Date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [41]:
print(df.index)
df.head()

DatetimeIndex(['2018-07-02', '2018-06-29', '2018-06-28', '2018-06-27',
               '2018-06-26', '2018-06-25', '2018-06-22', '2018-06-21',
               '2018-06-20', '2018-06-19', '2018-06-18', '2018-06-15',
               '2018-06-14', '2018-06-12', '2018-06-11', '2018-06-08',
               '2018-06-07', '2018-06-05', '2018-06-04', '2018-06-01'],
              dtype='datetime64[ns]', name='New_Date', freq=None)

            Close  Start   High    Low  Volume
New_Date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [42]:
# index 정렬
df.sort_index(inplace=True)
df.head()

            Close  Start   High    Low  Volume
New_Date
2018-06-01  11900  11800  12100  11750   32062
2018-06-04  11900  11900  12200  11700   25171
2018-06-05  12150  11800  12250  11800   42485
2018-06-07  11950  12200  12300  11900   49088
2018-06-08  11950  11950  12200  11800   59258

In [43]:
# 데이터프레임에 대해 [] 접근자를 사용할 때, 날짜를 기반으로 슬라이싱 가능. 슬라이스이 양 끝을 포함한다
df_ymd_range = df.loc['2018-06-26' : '2018-06-29']
df_ymd_range

            Close  Start   High    Low  Volume
New_Date
2018-06-26  10800  10900  11000  10700   63039
2018-06-27  10900  10800  11050  10500  133548
2018-06-28  10400  10900  10950  10150  155769
2018-06-29  10700  10550  10900   9990  170253

In [57]:
df_ym = df.loc['2018-07', 'Start':'High']
df_ym.index.name = None     # 인덱스 이름 삭제 'New_Date'
df_ym

            Start   High
2018-07-02  10850  10900

In [59]:
import numpy as np
import pandas as pd
from datetime import datetime

dates = [datetime(2011,1,2),datetime(2011,1,5),
        datetime(2011,1,7),datetime(2011,1,8),
        datetime(2011,1,10),datetime(2011,1,12)]
ts = pd.Series(np.random.randn(6),index=dates)
ts

2011-01-02   -0.400686
2011-01-05    0.075917
2011-01-07    0.071473
2011-01-08    1.037256
2011-01-10    0.795355
2011-01-12   -0.846835
dtype: float64

In [60]:
df = pd.DataFrame(ts, columns=['Value'])
df

               Value
2011-01-02 -0.400686
2011-01-05  0.075917
2011-01-07  0.071473
2011-01-08  1.037256
2011-01-10  0.795355
2011-01-12 -0.846835

In [66]:
print(ts.index, '\n')

# 2 스텝
print(ts[::2], '\n')

# 기존 ts 와 2 스텝을 더함 (없는 쪽은 Na로 반환됨)
print(ts + ts[::2], '\n')

ts.index[0]

DatetimeIndex(['2011-01-02', '2011-01-05', '2011-01-07', '2011-01-08',
               '2011-01-10', '2011-01-12'],
              dtype='datetime64[ns]', freq=None)

2011-01-02   -0.400686
2011-01-07    0.071473
2011-01-10    0.795355
dtype: float64

2011-01-02   -0.801372
2011-01-05         NaN
2011-01-07    0.142945
2011-01-08         NaN
2011-01-10    1.590710
2011-01-12         NaN
dtype: float64

Timestamp('2011-01-02 00:00:00')

####datetime vs Timestamp
- datetime은 Python 표준 라이브러리에서 제공
- Timestamp는 pandas 라이브러이에서 제공
- Timestamp는 pandas의 다른 데이터 구조와의 호환성이 좋으며, 시계열 데이터를 다룰 때 유리
- Timestamp는 datetime 객체의 기능을 확장하여 시계열 분석에 필요한 추가 기능을 제공

In [68]:
# datetime <-> timestamp : 서로 바꿀수 있다
dt1 = datetime(2011, 1, 2)
ts1 = pd.Timestamp(dt1)
print(ts1, type(ts1))

ts1 = pd.Timestamp('2011-01-02')
dt1 = ts1.to_pydatetime()
print(dt1, type(dt1))

2011-01-02 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
2011-01-02 00:00:00 <class 'datetime.datetime'>

In [71]:
# Indexing, Selection, Subsetting
stamp = ts.index[2] #stamp에는 인덱스 2인 2011-01-07이 저장
print(stamp)
ts[stamp]   # ts[2011-01-07]에 대한 값 반환

2011-01-07 00:00:00

0.0714725327962437

In [74]:
# 서로 다른 날짜 형식을 사용하지만, pandas는 이러한 형식들을 자동으로 인식하고 적절한 날짜로 변환
# 2011-01-10    0.795355
print(ts['1/10/2011'], type(ts['1/10/2011']))
print(ts['20110110'], type(ts['20110110']))

0.7953552435180362 <class 'numpy.float64'>
0.7953552435180362 <class 'numpy.float64'>

In [76]:
longer_ts = pd.Series(np.random.rand(365), index=pd.date_range('11/30/2023', periods=365))
longer_ts

2023-11-30    0.514370
2023-12-01    0.234729
2023-12-02    0.529845
2023-12-03    0.953748
2023-12-04    0.476813
                ...
2024-11-24    0.796589
2024-11-25    0.417324
2024-11-26    0.098861
2024-11-27    0.502648
2024-11-28    0.687858
Freq: D, Length: 365, dtype: float64

In [78]:
longer_ts = pd.Series(np.random.rand(1000), index=pd.date_range('1/1/2000', periods=1000))
longer_ts

2000-01-01    0.774141
2000-01-02    0.750547
2000-01-03    0.645463
2000-01-04    0.144849
2000-01-05    0.575363
                ...
2002-09-22    0.411071
2002-09-23    0.474473
2002-09-24    0.707383
2002-09-25    0.911879
2002-09-26    0.021228
Freq: D, Length: 1000, dtype: float64

In [79]:
longer_ts['2001-05'][:5]    # [:5] 5개까지

2001-05-01    0.738727
2001-05-02    0.853956
2001-05-03    0.229714
2001-05-04    0.644879
2001-05-05    0.038914
Freq: D, dtype: float64

In [80]:
ts[datetime(2011, 1, 7):]   # 인덱싱 7일 이후 :

2011-01-07    0.071473
2011-01-08    1.037256
2011-01-10    0.795355
2011-01-12   -0.846835
dtype: float64

####truncate

In [87]:
# truncate
print(ts.truncate(before='2011-01-05', after='2011-01-10'), '\n')

# 날짜 형식이 바뀌어도 상관없음
print(ts.truncate(after='2011-01-09'), '\n')
print(ts.truncate(after='1/9/2011'), '\n')

# after는 정한 날짜 전 / before는 정한 날짜 뒤
print(ts.truncate(after='2011-01-09'), '\n')
print(ts.truncate(before='2011-01-09'))

2011-01-05    0.075917
2011-01-07    0.071473
2011-01-08    1.037256
2011-01-10    0.795355
dtype: float64

2011-01-02   -0.400686
2011-01-05    0.075917
2011-01-07    0.071473
2011-01-08    1.037256
dtype: float64

2011-01-02   -0.400686
2011-01-05    0.075917
2011-01-07    0.071473
2011-01-08    1.037256
dtype: float64

2011-01-02   -0.400686
2011-01-05    0.075917
2011-01-07    0.071473
2011-01-08    1.037256
dtype: float64

2011-01-10    0.795355
2011-01-12   -0.846835
dtype: float64

In [90]:
from datetime import datetime
from datetime import timedelta

now = datetime.now()
in_two_weeks = now + timedelta(weeks=2)
pd.date_range(datetime.now(), in_two_weeks)

DatetimeIndex(['2024-06-04 01:26:53.609851', '2024-06-05 01:26:53.609851',
               '2024-06-06 01:26:53.609851', '2024-06-07 01:26:53.609851',
               '2024-06-08 01:26:53.609851', '2024-06-09 01:26:53.609851',
               '2024-06-10 01:26:53.609851', '2024-06-11 01:26:53.609851',
               '2024-06-12 01:26:53.609851', '2024-06-13 01:26:53.609851',
               '2024-06-14 01:26:53.609851', '2024-06-15 01:26:53.609851',
               '2024-06-16 01:26:53.609851', '2024-06-17 01:26:53.609851'],
              dtype='datetime64[ns]', freq='D')

####period

In [94]:
# periods 매개변수는 date_range 함수에 전달 된 시작날짜와 종료날짜를 periods 매개변수에 전달 된 기준의 수만큼 동일하게 나누어 출력
ts = pd.date_range(start='2023-11-01', end='2023-11-30', periods = 10)
ts

DatetimeIndex(['2023-11-01 00:00:00', '2023-11-04 05:20:00',
               '2023-11-07 10:40:00', '2023-11-10 16:00:00',
               '2023-11-13 21:20:00', '2023-11-17 02:40:00',
               '2023-11-20 08:00:00', '2023-11-23 13:20:00',
               '2023-11-26 18:40:00', '2023-11-30 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [96]:
df = pd.DataFrame(np.arange(10), index = ts, columns=['value'])
df

                     value
2023-11-01 00:00:00      0
2023-11-04 05:20:00      1
2023-11-07 10:40:00      2
2023-11-10 16:00:00      3
2023-11-13 21:20:00      4
2023-11-17 02:40:00      5
2023-11-20 08:00:00      6
2023-11-23 13:20:00      7
2023-11-26 18:40:00      8
2023-11-30 00:00:00      9

####normalize=True 옵션

In [97]:
# normalize=True 옵션은 pd.date_range 함수에서 날짜와 시간을 생성할 때 시간 정보를 제거
pd.date_range('2012-05-02 12:52:31', periods = 5, normalize = True)

DatetimeIndex(['2012-05-02', '2012-05-03', '2012-05-04', '2012-05-05',
               '2012-05-06'],
              dtype='datetime64[ns]', freq='D')

####freq 매개변수에 사용되는 Frequncy strings
- A calendar year end frequency
- B   business day frequency
- C   custom business day frequency
- D   calendar day frequency
- W   weekly frequency
- M   month end frequency
- SM   semi-month end frequency (15th and end of month)
- BM   business month end frequency
- CBM   custom business month end frequency
- MS   month start frequency
- SMS   semi-month start frequency (1st and 15th)
- BMS   business month start frequency
- CBMS   custom business month start frequency
- Q   quarter end frequency

In [101]:
import numpy as np
# W-WED 매주 수요일 픽업
dates = pd.date_range('11/30/2023', periods=10, freq='W-WED')
print(dates)

DatetimeIndex(['2023-12-06', '2023-12-13', '2023-12-20', '2023-12-27',
               '2024-01-03', '2024-01-10', '2024-01-17', '2024-01-24',
               '2024-01-31', '2024-02-07'],
              dtype='datetime64[ns]', freq='W-WED')

예제

In [107]:
import pandas as pd
import numpy as np

np.random.randint(3, size=10)

df = pd.DataFrame(np.random.randint(3, size=10), index=dates, columns=['운동시간'])
df

            운동시간
2023-12-06     1
2023-12-13     0
2023-12-20     0
2023-12-27     0
2024-01-03     0
2024-01-10     0
2024-01-17     1
2024-01-24     2
2024-01-31     1
2024-02-07     1

In [111]:
np.random.seed(0)
long_df = pd.DataFrame(np.random.randn(10, 4), index=dates, columns=['Colorado', 'Texas', 'New York', 'Ohio'])
print(long_df, '\n')

# 1월의 데이터만 출력
print(long_df.loc['2024-01'], '\n')

# 2024년 데이터만 출력
print(long_df.loc['2024'])

            Colorado     Texas  New York      Ohio
2023-12-06  1.764052  0.400157  0.978738  2.240893
2023-12-13  1.867558 -0.977278  0.950088 -0.151357
2023-12-20 -0.103219  0.410599  0.144044  1.454274
2023-12-27  0.761038  0.121675  0.443863  0.333674
2024-01-03  1.494079 -0.205158  0.313068 -0.854096
2024-01-10 -2.552990  0.653619  0.864436 -0.742165
2024-01-17  2.269755 -1.454366  0.045759 -0.187184
2024-01-24  1.532779  1.469359  0.154947  0.378163
2024-01-31 -0.887786 -1.980796 -0.347912  0.156349
2024-02-07  1.230291  1.202380 -0.387327 -0.302303

            Colorado     Texas  New York      Ohio
2024-01-03  1.494079 -0.205158  0.313068 -0.854096
2024-01-10 -2.552990  0.653619  0.864436 -0.742165
2024-01-17  2.269755 -1.454366  0.045759 -0.187184
2024-01-24  1.532779  1.469359  0.154947  0.378163
2024-01-31 -0.887786 -1.980796 -0.347912  0.156349

            Colorado     Texas  New York      Ohio
2024-01-03  1.494079 -0.205158  0.313068 -0.854096
2024-01-10 -2.552990  0.653619  0.864436 -0.742165
2024-01-17  2.269755 -1.454366  0.045759 -0.187184
2024-01-24  1.532779  1.469359  0.154947  0.378163
2024-01-31 -0.887786 -1.980796 -0.347912  0.156349
2024-02-07  1.230291  1.202380 -0.387327 -0.302303

####중복 날짜

In [112]:
dates = pd.DatetimeIndex(['1/1/2000','1/2/2000','1/2/2000','1/2/2000',
                         '1/3/2000'])
dup_ts = pd.Series(np.arange(5),index=dates)
dup_ts

2000-01-01    0
2000-01-02    1
2000-01-02    2
2000-01-02    3
2000-01-03    4
dtype: int64

In [113]:
dup_ts.index.is_unique

False

In [114]:
print(dup_ts['1/3/2000'], '\n')  # not duplicated의 경우 스칼라 값
print(dup_ts['1/2/2000'])       # duplicated의 경우 슬라이스 출력

4

2000-01-02    1
2000-01-02    2
2000-01-02    3
dtype: int64

####groupby

In [118]:
grouped = dup_ts.groupby(level=0)
print(grouped.mean(), '\n')
grouped.count()

2000-01-01    0.0
2000-01-02    2.0
2000-01-03    4.0
dtype: float64

2000-01-01    1
2000-01-02    3
2000-01-03    1
dtype: int64

In [121]:
print(pd.date_range('2000-01-01', '2000-01-03 23:59', freq = '4h'), '\n')
print(pd.date_range('2000-01-01 23:59', '2000-01-03 23:59', freq = '4h'), '\n')

DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 04:00:00',
               '2000-01-01 08:00:00', '2000-01-01 12:00:00',
               '2000-01-01 16:00:00', '2000-01-01 20:00:00',
               '2000-01-02 00:00:00', '2000-01-02 04:00:00',
               '2000-01-02 08:00:00', '2000-01-02 12:00:00',
               '2000-01-02 16:00:00', '2000-01-02 20:00:00',
               '2000-01-03 00:00:00', '2000-01-03 04:00:00',
               '2000-01-03 08:00:00', '2000-01-03 12:00:00',
               '2000-01-03 16:00:00', '2000-01-03 20:00:00'],
              dtype='datetime64[ns]', freq='4H')

DatetimeIndex(['2000-01-01 23:59:00', '2000-01-02 03:59:00',
               '2000-01-02 07:59:00', '2000-01-02 11:59:00',
               '2000-01-02 15:59:00', '2000-01-02 19:59:00',
               '2000-01-02 23:59:00', '2000-01-03 03:59:00',
               '2000-01-03 07:59:00', '2000-01-03 11:59:00',
               '2000-01-03 15:59:00', '2000-01-03 19:59:00',
               '2000-01-03 23:59:00'],
              dtype='datetime64[ns]', freq='4H')

In [122]:
# 오프셋 객체들을 새로운 시간을 계싼하거나 시계열 데이터를 조작하는 데 사용
from pandas.tseries.offsets import Hour, Minute
Hour(2) + Minute(30)

In [123]:
pd.date_range('2000-01-01', periods=10, freq = '1h30min')

DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 01:30:00',
               '2000-01-01 03:00:00', '2000-01-01 04:30:00',
               '2000-01-01 06:00:00', '2000-01-01 07:30:00',
               '2000-01-01 09:00:00', '2000-01-01 10:30:00',
               '2000-01-01 12:00:00', '2000-01-01 13:30:00'],
              dtype='datetime64[ns]', freq='90T')

In [124]:
# Week of month, 매월 세 번째 금요일에 해당하는 날짜를 생성
rng = pd.date_range('2000-01-01', '2012-09-01', freq = 'WOM-3FRI')
print(rng)

DatetimeIndex(['2000-01-21', '2000-02-18', '2000-03-17', '2000-04-21',
               '2000-05-19', '2000-06-16', '2000-07-21', '2000-08-18',
               '2000-09-15', '2000-10-20',
               ...
               '2011-11-18', '2011-12-16', '2012-01-20', '2012-02-17',
               '2012-03-16', '2012-04-20', '2012-05-18', '2012-06-15',
               '2012-07-20', '2012-08-17'],
              dtype='datetime64[ns]', length=152, freq='WOM-3FRI')

In [125]:
from pandas.tseries.offsets import Day, MonthEnd
now = datetime(2011, 11, 17)
now + 3 * Day()

Timestamp('2011-11-20 00:00:00')

In [127]:
# 현재 날짜를 기준으로 가장 가까운 월말 날짜로 이동
offset = MonthEnd()
print(offset.rollforward(now))

# 현재 날짜를 기준으로 가장 가까운 이전 월말 날짜로 이동
offset.rollback(now)

2011-11-30 00:00:00

Timestamp('2011-10-31 00:00:00')

In [129]:
# 기간을 타임스탬프로 변환
import numpy as np

rng = pd.period_range('2000-01-01', periods=3, freq='M')
ts = pd.Series(np.random.randn(3), index  = rng)
print(ts, '\n')
print(type(ts))

2000-01    1.950775
2000-02   -0.509652
2000-03   -0.438074
Freq: M, dtype: float64

<class 'pandas.core.series.Series'>

In [130]:
ts.to_timestamp(how='end')

2000-01-31 23:59:59.999999999    1.950775
2000-02-29 23:59:59.999999999   -0.509652
2000-03-31 23:59:59.999999999   -0.438074
dtype: float64